### ISSUE TITLE
Change folder name

### ISSUE THREAD

**Issue by rafaelcn** [brain-labs/brainduino#2]
Should we change the name of the folder from `Brain` to `Brainduino` as it is not Brain itself. It would look more semantic to the project.

**Comment by luizperes** [comment]
I will do it! Thanks!

**Comment by luizperes** [comment]
We've gotta a problem actually, @rafaelcn ... I think that we should leave that as **Brain**, because I want the user to know that Brain is an actual programming language, otherwise it will look like `Brainduino  brain = Brainduino(&Serial, NULL, NULL)` instead of  `Brain  brain = Brain(&Serial, NULL, NULL)`...

Well, let me check if we can change only the library folder name.

**Comment by rafaelcn** [comment]
:thought_balloon: 

That would be odd, waiting for a response then. :-)

**Comment by luizperes** [comment]
That is solved here https://github.com/brain-labs/brainduino/commit/45c1c098316ded46767af821ed3c688851a0d04b @rafaelcn, thanks for that! Thanks also for creating the `dev` branch as well! I had forgotten to do it!

**Comment by rafaelcn** [comment]
No problem at all. Glad to see we could change that!
